name: gsoc_unicode_app
description: "GSOC Unicode Flutter App"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  app_tracking_transparency: ^2.0.4
  auto_route: ^10.0.1
  auto_size_text: ^3.0.0
  clipboard: ^0.1.3
  csv: ^6.0.0
  cupertino_icons: ^1.0.6
  dartdoc: ^8.3.4
  device_info_plus: ^11.4.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_bloc: ^9.1.0
  flutter_hooks: ^0.21.2
  flutter_local_notifications: ^19.2.0
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.0.9
  flutter_typeahead: ^5.2.0
  fluttertoast: ^8.2.8
  freezed_annotation: ^2.4.1
  get_it: ^8.0.0
  gif: ^2.3.0
  google_fonts: ^6.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.2.1
  # icu:
  #   git:
  #     url: git@github.com:unicode-org/icu4x.git
  #     path: ffi/dart
  json_annotation: ^4.8.1
  lottie: ^3.1.2
  multi_dropdown: ^3.0.1
  path_provider: ^2.1.4
  responsive_framework: ^1.1.0
  rxdart: ^0.28.0
  share_plus: ^11.0.0
  shimmer: ^3.0.0
  simple_animations: ^5.0.2

dev_dependencies:
  auto_route_generator: ^10.0.1
  bloc_test: ^10.0.0
  build_runner: ^2.4.9
  flutter_gen_runner: ^5.4.0
  flutter_lints: ^6.0.0
  flutter_localization: ^0.3.2
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  integration_test:
    sdk: flutter
  intl_utils: ^2.8.7
  json_serializable: ^6.7.1
  mockito: ^5.4.6
  very_good_analysis: ^9.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/unicode_dummy_data.csv
